#spring:
#  application:
#    name: commondblib
#  datasource:
#    url: jdbc:postgresql://localhost:5432/omniservedb
#    username: postgres
#    password: Admin@123
#  jpa:
#    hibernate:
#      ddl-auto: create    # or validate, create, etc.
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect